#!/bin/sh
# Entrypoint script for dbt-bootcamp-setup container

# Pre-create static directory so Streamlit enables static file serving
# The actual container-info.json is generated by the Streamlit app at startup
mkdir -p /app/static

# Start Streamlit
exec /app/.venv/bin/streamlit run streamlit_app.py \
    --server.address 0.0.0.0 \
    --server.port 8501 \
    --server.headless true